name: prdiff_agent
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - ca-certificates
  - openssl
  - sqlite
  - pip:
      - langchain==1.2.6
      - langchain-core==1.2.7
      - langchain-ollama==1.0.1
      - langgraph==1.0.6
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.6
      - langgraph-sdk==0.3.3
      - langsmith==0.6.4
      - ollama==0.6.1
      - pygithub==2.8.1
      - python-dotenv==1.2.1
      - pydantic==2.12.5
      - requests==2.32.5
      - tenacity==9.1.2
      - anyio==4.12.1
      - httpx==0.28.1